index.html
=> Fix wdisplays text

src/index.html
=> feat: add ydotool - fix #2

src/index.html
=> feat: remove vlc (fix #13) and link to issue for Chromium (fix #14)

src/index.html
I did no add forks of swaylock, I hope I did not forget any other projects
though!
=> feat: add screen lockers - fix #9

src/css/normalize.css, src/css/styles.css, src/index.html, src/js/theme.js
=> feat: add dark theme with media query support - fix #21

src/index.html
Similar to `ssh -X` but works better with accelerated windows.
=> feat: add network transparency

src/index.html
=> feat(browsers): add qutebrowser - fix #32

src/index.html
Signed-off-by: Bogomil Vasilev <smirky@smirky.net>
=> feat: add Dolphin and Konsole to the list

config.toml
=> fix: correct typo in page title

layouts/index.html
Thanks @asdfjkluiop for mentioning `wlrobs`.
----
#
=> feat(obs): add necessary plugin, wlrobs - fix #39

layouts/index.html
Thanks to @asdfjkluiop.
----
#
=> fix: improve wording - fix #40

layouts/index.html
Thanks to @daveriedstra.
----
#
=> feat: add ulauncher - fix #38

layouts/index.html, layouts/partials/footer.html, layouts/partials/head.html
=> feat: re-introduce file managers - fix #35

layouts/404.html, layouts/index.html, layouts/partials/footer.html, layouts/partials/title.html, src/css/main.css
=> feat: add a 404 page

static/_headers
=> chore(csp): update report url

layouts/index.html
=> feat(browsers): add Chromium as a "normal" candidate - fix #14

layouts/index.html
Shameless self-plug!
Thanks for maintaining this list.
=> feat: add shotman as a screenshooting tool

layouts/index.html
=> feat(terminal emulators): add foot

layouts/index.html
useful tool, can replace xdotool type
https://github.com/atx/wtype
=> feat: add wtype as user simulating tool

layouts/index.html
Flameshot supports wayland now! See the [changelog](https://flameshot.org/changelog/)
=> feat: add flameshot to screenshot tools list

layouts/index.html
adds onagre and nwg-launchers in App Launcher; fnott in notification daemon
=> feat: several additions

layouts/index.html
https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty
=> feat: remove termite (retired)

layouts/index.html
sorry about making a new PR
i made so many mistakes on #92 so i have made a new branch upstream with aggregated list from patch-1 repo
=> feat: add compositors, power menu, dock and document viewer #92

layouts/index.html
=> Include item for login managers

layouts/index.html
=> feat: add QtGreet

layouts/index.html
First entry: Color management and HDR
Also removed stray </small> tag.
=> Add "Missing" section
