mpsq/arewewaylandyet

index.html

In practice only GNOME and KDE offer reasonable Wayland support "out of the box" as a complete desktop environment nowadays. It's worth a mention.

Add desktop environments

---

layouts/index.html

`nemo` has worked fine on wayland for many months now.

feat: add nemo as a file manager

---

layouts/index.html

fix: correct information for KDE Wayland on NVIDIA hardware

---

layouts/index.html

KDE (the desktop environement) was last released with KDE3. It's now called Plasma Desktop or simply Plasma.

fix: correct KDE/Plasma name

---

layouts/index.html

gmenu has migrated to a new git hosting site.

fix: update gmenu repository URL

---

layouts/index.html

chore: fix naming, casing, sorting and URLs

---

layouts/index.html

Removes text about the OBS plugin. Since the latest release now works without a plugin.
fixes #71
I have:

fix: OBS now works without the need of a plugin

---

layouts/index.html

Fixes #100
I added Okular
I have:

feat: add Okular document viewer

---

layouts/index.html

This adds wlopm to list of output configuration tools.
I have:

feat: add wlopm to output configuration section

---

layouts/index.html

Just adds Opera, solving #111 
I have:

feat: add opera browser (fixes #111)

---

layouts/index.html

Adds an "Image editor"  session with Inkscape on it. Solves #78 
I have:

feat: add Inkscape (solves #78)

---

layouts/index.html

Adds `Terminator` to the terminal session
I have:

feat: add Terminator (solves #75)

---

layouts/index.html

Adds an "Email client (GUI)" session with thunderbird and evolution (both tested by me to ensure they work with wayland)
I have:

feat: add email section (solves #43)

---

layouts/index.html

Adds a "Keyboard remapper" session (a must have for 60% keuboard users). Solves #67 
I have:

feat: add keyboard remapper (closes #67)

---

layouts/index.html

Adds dynamic tiling Wayland compositor `vivarium` to the `Tiling compositor` section.
I have:

feat: add vivarium window manager

---

layouts/index.html

Added SwayNotificationCenter to the Notification daemon section
I have:

feat: add SwayNotificationCenter to Notification daemon section

---

layouts/index.html

Add missing comma
This was annoying tf out of me
I have:

fix: add missing comma

---

layouts/index.html

Added [swayimg](https://github.com/artemsen/swayimg) to the list of image viewers
I have:

feat: add swayimg to list of image viewers

---

layouts/index.html

feat: add wpaperd to Wallpaper manager section

---

layouts/index.html

WezTerm, a Rust terminal emulator, provides OpenGL rendering, tabs, split panes, multiplexing, font ligatures, support for many modern terminal protocol extensions (hyperlinks, true color, iTerm2 inline images, etc.), all backed by a powerful and flexible Lua-based configuration.
I have:

feat: add WezTerm to the list of terminals

---

layouts/index.html

Short description of the changes: Added Qtile window manager to the list since it can now be run as a Wayland compositor
I have:

feat: add Qtile to tiling compositor list

---

layouts/index.html

Add nwg-displays to list of output managers and delete some unnecessary slashes in other links
I have:

feat: add nwg-displays to list of output managers

---

layouts/index.html

wmenu is a dmenu-fork adapted to work on wayland. Added the project link to the list of application launchers. It has no website.
I have:

feat: add wmenu to list of application launchers

---

layouts/index.html

feat: add keyd and kmonad in keyboard remapper section

---

layouts/index.html

Added xremap, a keyboard remapper that's been running flawlessly on Wayland
I have:
- [\*] 🤓 checked BOTH the name and the casing of the project(s) I am adding ("GNOME Terminal" and not "gnome-terminal", "bemenu" and not "Bemenu", etc.). Both Xremap and xremap is used in the README. I went with the project name's casing

Add xremap

---

layouts/index.html

Add Gimp and Krita to Image editor
I have:

Add Gimp and Krita to Image editor

---

layouts/index.html

hi! this add [cliphist](https://github.com/sentriz/cliphist) as a clipboard manager
quite similar to clipman which is already there (and quite a nice tool), but I personally prefer cliphist because 
- it makes no assumptions about a picker tool. you can use whatever you like
- clipboard is preserved byte for byte, no hidden character messups
- images/non-text also work
also I think manjaro sway edition also use it now
thanks! 
I have:

feat: add cliphist

---

layouts/index.html

Short description of the changes: Adds Hyprland to the tiling compositor list and solves [#139](https://github.com/mpsq/arewewaylandyet/issues/139)
I have:

feat: add Hyprland to the tiling compositor list (closes #139)

---

layouts/index.html

Add hyprpaper wallpaper manager and hyprpicker color picker.
I have:

feat: add hyprpaper and hyprpicker

---

layouts/index.html

Nowadays, sway seems to run on nouveau quite well. The current page gives the impression it wouldn't work at all.
Fixes #149.

feat: add note about sway/wlroots working on nouveau

---

layouts/index.html

[gcolor3](https://gitlab.gnome.org/World/gcolor3) supports wayland nicely on ubuntu 22.04, if you build it from source.
I have:

feat: add gcolor3

---

layouts/index.html

Displaylink driver makes possible for some monitor adapters to work, and it's widely used on office computers where you need to connect an HDMI to an USB for example, and it's multiplataform (Windows, Mac and Linux).
Unfortunately, it only works for Gnome Wayland, KDE Wayland and xserver in general, not Sway/wlroots
I have:
- [ x 🔗 checked that the link I am using refers to the root of the project (example, https://mpv.io) or GitHub repo **if the first is not available**

Add missing displaylink support for Sway/wlroots

---

layouts/index.html

Short description of the changes: Adds [`swww`](https://github.com/Horus645/swww) to the Wallpaper manager section.
I have:

Add swww to Wallpaper managers

---

layouts/index.html

Short description of the changes: The project is now hosted on sr.ht, and the GitLab repo has been archived. Closes #176 .
I have:

update shotman URL

---

layouts/index.html

Added [Anyrun](https://github.com/Kirottu/anyrun) to the Application launchers section.
I have:

Added Anyrun to Application launchers
